name: Deployment
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.6'
      - name: Build and zip
        env:
          GIN_ENV_MODE: dev
          PORT: ${{ secrets.PORT }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_ENDPOINT: ${{ secrets.DB_PASSWORD }}

        run: |
          go build -o bin/application main.go
          zip -r application.zip .
      - name: Upload Go executable
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: application.zip
  deploy:
    needs: build
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Download Go executable
        uses: actions/download-artifact@v2
        with:
          name: artifact
        #Deploy the artifact into AWS Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v13
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          use_existing_version_if_available: false
          application_name: full-stack-project
          environment_name: full-stack-project-env
          version_label: ${{ github.SHA }}
          region: us-east-1
          deployment_package: application.zip